precompile( inject, (TwObj{TwTreeData}, Symbol ) )
precompile( inject, (TwObj{TwTreeData}, String ) )
precompile( inject, (TwObj{TwDfTableData}, Symbol ) )
precompile( inject, (TwObj{TwDfTableData}, String ) )
precompile( inject, (TwObj{TwEntryData}, Symbol ) )
precompile( inject, (TwObj{TwEntryData}, String ) )
precompile( inject, (TwObj{TwScreenData}, Symbol ) )
precompile( inject, (TwObj{TwScreenData}, String ) )
