precompile( inject, (TwObj{TwTreeData}, Symbol ) )
precompile( inject, (TwObj{TwTreeData}, ASCIIString ) )
precompile( inject, (TwObj{TwDfTableData}, Symbol ) )
precompile( inject, (TwObj{TwDfTableData}, ASCIIString ) )
precompile( inject, (TwObj{TwEntryData}, Symbol ) )
precompile( inject, (TwObj{TwEntryData}, ASCIIString ) )
precompile( inject, (TwObj{TwScreenData}, Symbol ) )
precompile( inject, (TwObj{TwScreenData}, ASCIIString ) )
